# Generated by Django 5.0.1 on 2024-02-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sellar',
            new_name='seller',
        ),
    ]
