# Generated by Django 5.0.1 on 2024-02-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_listing_brand_listing_color_listing_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
